AndrewSchembri62BShoppingCart/PresentationWebApp/Controllers/CartsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingCart.Application.Interfaces;
using ShoppingCart.Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PresentationWebApp.Controllers
{
    public class CartsController : Controller
    {
        private readonly ICartsService _cartsService;
        private readonly IProductsService _productsService;
        private readonly IOrderDetailsService _orderDetailsService;
        private readonly IOrdersService _ordersService;
        private readonly ILogger<CartsController> _logger;
        private IWebHostEnvironment _env;

        public CartsController(IProductsService productsService, IOrdersService ordersService, IOrderDetailsService orderDetailsService, ILogger<CartsController> logger, ICartsService cartsService, IWebHostEnvironment env)
        {
            _orderDetailsService = orderDetailsService;
            _ordersService = ordersService;
            _productsService = productsService;
            _cartsService = cartsService;
            _logger = logger;
            _env = env;
        }

        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public IActionResult Index()
        {
            string email = User.Identity.Name; //User Email
            var list = _cartsService.GetCarts(email); //Get From Cart
            return View(list); //View User Cart
        }

        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public IActionResult Delete(int id)
        {
            try
            {
                _cartsService.DeleteFromCart(id); //Delete Product From Cart
                TempData["feedback"] = "Product was deleted";
            }
            catch (Exception ex)
            {
                _logger.LogError("Product Was Not Deleted! " + ex);
                TempData["warning"] = "Product was not deleted";
            }

            return RedirectToAction("Index", new { email = User.Identity.Name }); //Redircet with User Email
        }

        [Authorize(Roles = "User, Admin")]
        public IActionResult AddOrder()
        {
            try
            {
                string email = User.Identity.Name;
                if (email != null)
                {
                    var CartToAdd = _cartsService.GetCarts(email); //Get All From Cart
                    if (CartToAdd.Count > 0) //If Cart Not Empty
                    {
                        var orderModel = new OrderViewModel();
                        orderModel.DatePlaced = DateTime.Now; //Setting Order DateTime
                        orderModel.UserEmail = User.Identity.Name; //Setting Order Email
                        int orderId = _ordersService.AddOrder(orderModel); //Adding Order
                        string feedback = "Order Created";

                        foreach (var c in CartToAdd) //Loop Every Item in Cart
                        {
                            if (c.Product.Stock > 0 && c.Product.Stock >= c.Quantity) { //If Quantity Wanted is Greater than Stock Keep Item in Cart and Dont Create Order
                                double price = (c.Quantity * c.Product.Price); //Setting Price is Product Price for Quantity
                                int quantity = c.Quantity; // Setting Quantity
                                Guid productId = c.Product.Id;  //Set Product Id
                                
                                _orderDetailsService.AddOrderDetail(orderId, productId, quantity, price); //Add Order Detail
                                _cartsService.DeleteFromCart(c.Id); //Delete Product From Cart

                                _productsService.DecreaseStock(c.Product, c.Quantity); //Decrease From Stock
							}
							else
							{
                                feedback = "Order Created: Some Items Were Not Ordered";
							}
                        }

                        TempData["feedback"] = feedback;
                    }
                    else
                    {
                        TempData["warning"] = "Order was Not Created: Empty Cart";
                    }
				}
				else
				{
                    TempData["warning"] = "Order was Not Created: Invalid Email";
                }
            }
            catch (Exception ex) {
                _logger.LogError("Order Was Not Created! " + ex);
                TempData["warning"] = "Order was Not Created" + ex;
            }
            return RedirectToAction("Index");
        }
    }
}

AndrewSchembri62BShoppingCart/PresentationWebApp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingCart.Application.Interfaces;

namespace PresentationWebApp.Controllers
{
	public class OrdersController : Controller
	{
		private readonly ICartsService _cartsService;
		private readonly IOrdersService _ordersService;
		private readonly IOrderDetailsService _orderDetailsService;
		ILogger<OrdersController> _logger;
		private IWebHostEnvironment _env;

		public OrdersController(IOrdersService ordersService, IOrderDetailsService orderDetailsService, ICartsService cartsService, ILogger<OrdersController> logger, IWebHostEnvironment env)
		{
			_ordersService = ordersService;
			_orderDetailsService = orderDetailsService;
			_cartsService = cartsService;
			_logger = logger;
			_env = env;
		}

		[Authorize(Roles = "User, Admin")]
		public IActionResult Index(string email)
		{
			var list = _orderDetailsService.GetOrderDetails(email); //Get All Orders From Email
			return View(list);
		}
	}
}

AndrewSchembri62BShoppingCart/PresentationWebApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingCart.Application.Interfaces;
using ShoppingCart.Application.ViewModels;
using X.PagedList;

namespace PresentationWebApp.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductsService _productsService;
        private readonly ICartsService _cartsService;
        private readonly ICategoriesService _categoriesService;
        private readonly ILogger<ProductsController> _logger;
        private IWebHostEnvironment _env;
        public ProductsController(IProductsService productsService, ICategoriesService categoriesService,
             ICartsService cartsService, ILogger<ProductsController> logger, IWebHostEnvironment env )
        {
            _productsService = productsService;
            _categoriesService = categoriesService;
            _cartsService = cartsService;
            _logger = logger;
            _env = env;
        }

        //https://www.youtube.com/watch?v=vnxN_zBisIo
        public IActionResult Index(int? page) //Page Number
        {
            var pageNumber = page ?? 1; //If Page Number is Not Specified Page Number = 1
            var list = _productsService.GetProducts(); //Get All Products
            int pageSize = 10; //Specify Products Per Page
            var onePageOfProducts = list.ToPagedList(pageNumber, pageSize); //Give X.PagedList Parameters

            var listOfCategeories = _categoriesService.GetCategories(); //Categories For Filter
            ViewBag.Categories = listOfCategeories; //Set All Categories

            return View(onePageOfProducts); //Send List of Products
        }

        [HttpPost]
        public IActionResult Search(string keyword, int? page) //If Keyword Inserted
        {
            var pageNumber = page ?? 1;
            var list = _productsService.GetProducts(keyword).ToList(); //Get Products With Keyword

            var listOfCategeories = _categoriesService.GetCategories();
            ViewBag.Categories = listOfCategeories;

            return View("Index", list.ToPagedList(pageNumber, 10));
        }

        [HttpPost]
        public IActionResult SearchCategory(int category, int? page) //If Category Id inserted 
        {
            var pageNumber = page ?? 1;
            var list = _productsService.GetProducts(category).ToList(); //Get Products With Category

            var listOfCategeories = _categoriesService.GetCategories();
            ViewBag.Categories = listOfCategeories;

            return View("Index", list.ToPagedList(pageNumber, 10));
        }


        public IActionResult Details(Guid id)
        {
            var p = _productsService.GetProduct(id); //Get Details of Item
            return View(p);
        }

        [HttpGet]
        [Authorize (Roles ="Admin")]
        public IActionResult Create()
        {
            //fetch a list of categories
            var listOfCategeories = _categoriesService.GetCategories();

            //we pass the categories to the page
            ViewBag.Categories = listOfCategeories;

            return View();
        }

        //here details input by the user will be received
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(ProductViewModel data, IFormFile f)
        {
            try
            {
                if(f !=  null)
                {
                    if(f.FileName.Length > 0)
                    {
                        if (data.Stock > 0) {
                            string newFilename = Guid.NewGuid() + System.IO.Path.GetExtension(f.FileName);
                            string newFilenameWithAbsolutePath = _env.WebRootPath + @"\Images\" + newFilename;

                            using (var stream = System.IO.File.Create(newFilenameWithAbsolutePath))
                            {
                                f.CopyTo(stream);
                            }

                            data.ImageUrl = @"\Images\" + newFilename;

                            _productsService.AddProduct(data);

                            TempData["feedback"] = "Product was added successfully";
						}
						else{
                            TempData["warning"] = "Product Stock Cannot Be Less Than 1!";
                        }
					}
					else
					{
                        TempData["warning"] = "Product add an Image!";
                    }
				}
				else
				{
                    TempData["warning"] = "Product add an Image!";
                }


            }
            catch (Exception ex)
            {
                _logger.LogError("Product Was Not Added! " + ex);
                TempData["warning"] = "Product was not added!";
            }

           var listOfCategeories = _categoriesService.GetCategories();
           ViewBag.Categories = listOfCategeories;
           return View(data);
        
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Guid id)
        {
            try
            {
                _productsService.DeleteProduct(id); //Delete Product With Id
                TempData["feedback"] = "Product was deleted";
            }
            catch (Exception ex)
            {
                _logger.LogError("Product Was Not Deleted! " + ex);
                TempData["warning"] = "Product was not deleted";
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Hide(Guid id)
		{
            try
            {
                _productsService.HideProduct(id); //Hide Product With ID
                TempData["feedback"] = "Product is Now Hidden!";
            }
            catch (Exception ex)
            {
                _logger.LogError("Product Was Not Hidden! " + ex);
                TempData["warning"] = "Product is Not Hidden!";
            }

            return RedirectToAction("Index");
        }

        public IActionResult Show(Guid id)
        {
            try
            {
                _productsService.ShowProduct(id); //Show Product with ID
                TempData["feedback"] = "Product is Now Shown!";
            }
            catch (Exception ex)
            {
                _logger.LogError("Product Was Not Shown! " + ex);
                TempData["warning"] = "Product is Not Shown!";
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public IActionResult AddToCart(Guid id, int quantity)
        //public IActionResult AddToCart(Guid id, string email)
        {
            try
            {
                if (id != null && quantity > 0) {
                        _cartsService.AddToCart(_productsService.GetProduct(id), quantity, User.Identity.Name); //Add To Cart ProductID, with Quantity and Email
				}else
				{
                    TempData["warning"] = "Product was not added! (ID or Quantity Error)";

                }

                TempData["feedback"] = "Product was added successfully";
            }
            catch (Exception ex)
            {
                _logger.LogError("Product Was Not Added! " + ex);
                TempData["warning"] = "Product was not added! ";
            }

            return RedirectToAction("Index");
        }
    }
}

AndrewSchembri62BShoppingCart/PresentationWebApp/Views/Shared/SearchPartial.cshtml
<div class="col">
	<form class="form-inline my-4 form-group" method="post" action="/Products/Search">
		<input type="text" class="form-control w-50" placeholder="Search" name="keyword" />
		<button type="submit" class="btn btn-primary btn-block w-50">Search</button>
	</form>
</div>

AndrewSchembri62BShoppingCart/PresentationWebApp/Views/Shared/ViewCartsPartial.cshtml
@model IEnumerable<ShoppingCart.Application.ViewModels.CartViewModel>

@if (Model.Count() > 0) //If More than 0 Items in Cart
{ 
	@foreach (var c in Model)
	{
<div class="card card- bg-dark text-light h-50">
	<img src="@c.Product.ImageUrl" class="card-img-top img-fluid" style="height:300px;" alt="...">
	<div class="p-4">
		<p class="text-truncate">User: @c.Email</p>
		<p>Product: @c.Product.Name</p>
		<p>Quantity: @c.Quantity</p>
		<a href="/Carts/Delete?id=@c.Id" class="btn btn-danger btn-block"><i class="fas fa-trash"></i> Delete</a>
	</div>

	@{
		double price = c.Product.Price * c.Quantity;
	}

	<h4 class="mb-4 pb-0 pl-4">Total: &euro;@price</h4>
</div>
	}
}
else //Else Show Empty Cart
{
	<div class="alert alert-danger mx-auto my-4 w-75">Empty Cart</div>
}

AndrewSchembri62BShoppingCart/PresentationWebApp/Views/Shared/ViewOrdersPartial.cshtml
@model IEnumerable<ShoppingCart.Application.ViewModels.OrderDetailsViewModel> 
<!-- ORDERS -->

@if (Model.Count() > 0)
{
	@foreach (var o in Model)
	{
		<div class="bg-dark mt-4 mb-4 rounded">
			<div class="row w-100">
				<div class="jumbotron w-100">
					<div class="row">
						<div class="col">
							<p><b>User:</b> @o.Order.UserEmail</p>
							<p><b>Product:</b> @o.Product.Name</p>
							<p><b>Quantity:</b> @o.Quantity</p>
							<p><b>Price:</b> &euro;@o.Price</p>
						</div>
						<div class="col">
							<img src="@o.Product.ImageUrl" class="float-right" width="200">
						</div>
					</div>

					<div class="row">
						<a class="btn btn-warning float-right mx-2">ID: @o.Order.Id</a>
						<a class="btn btn-primary float-right text-light mx-2">Date: @o.Order.DatePlaced</a>
					</div>
				</div>
			</div>
		</div>
	}
}
else
{
	<div class="alert alert-danger mx-auto my-4 w-75">No Orders</div>
}

AndrewSchembri62BShoppingCart/PresentationWebApp/Views/Shared/ViewProductsPartial.cshtml
@model IEnumerable<ShoppingCart.Application.ViewModels.ProductViewModel>

@foreach (var p in Model)
{
	if (p.Disable == false || User.IsInRole("Admin")) //If Product Is Not Disabled
	{
	<div class="card card- bg-dark text-light h-50">
		<img src="@p.ImageUrl" class="card-img-top img-fluid" style="height:300px;" alt="...">
		<div class="p-4">
			<h5 class="card-title">@p.Name</h5>
			<p class="card-text">&euro;@p.Price</p>
			<a href="/Products/Details?id=@p.Id" class="btn btn-primary btn-block"><i class="fas fa-info"></i> View Specification</a>
			@if (User.IsInRole("Admin"))
			{
				<a href="/Products/Delete?id=@p.Id" class="btn btn-danger btn-block"><i class="fas fa-trash"></i> Delete</a>
				@if (p.Disable == true)
				{
					<a href="/Products/Show?id=@p.Id" class="btn btn-success btn-block"><i class="fas fa-eye"></i> Show</a>
				}
				else
				{
					<a href="/Products/Hide?id=@p.Id" class="btn btn-secondary btn-block"><i class="fas fa-eye"></i> Hide</a>
				}
			}

			@if (User.IsInRole("User") || User.IsInRole("Admin"))
			{
				<br/>
				<form method="get" asp-controller="Products" asp-action="AddToCart" class="row w-100 mx-auto">
					<div class="col-6">
						<input type="hidden" name="id" value="@p.Id"/>
						<input type="number" name="quantity" class="form-control h-100" value="1" min="1"/>
					</div>

					<div class="col-6">
						<button type="submit" class="btn btn-success btn-block"><i class="fas fa-shopping-cart"></i> Add to Cart</button>
					</div>
				</form>
			}
		</div>
	</div>
	}
}

AndrewSchembri62BShoppingCart/PresentationWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - PresentationWebApp</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark text-light border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Home</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Products" asp-action="Create"><i class="fa fa-plus"></i> Create Product</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Products" asp-action="Index"><i class="fa fa-box"></i> Products</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" asp-controller="Carts" asp-action="Index" asp-route-email="@User.Identity.Name"><i class="fas fa-shopping-cart"></i> Cart</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" asp-controller="Orders" asp-action="Index" asp-route-email="@User.Identity.Name"><i class="fas fa-list"></i> Orders</a>
						</li>
					</ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">

            @if (TempData["feedback"] != null)
            {
                <div class="alert alert-primary" role="alert">
                    @TempData["feedback"]
                </div>
            }

            @if (TempData["warning"] != null)
            {
                <div class="alert alert-warning" role="alert">
                    @TempData["warning"]
                </div>
            }


            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Shopping Cart Application
        </div>
    </footer>
  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>